src/app/models/post.py
from app.extensions import db
from datetime import datetime


class Post(db.Model):
    __tablename__ = 'posts'

    id = db.Column(db.Integer, primary_key=True)
    caption = db.Column(db.String(140), nullable=True)
    photo_url = db.Column(db.String)
    timestamp = db.Column(db.DateTime, index=True, default=datetime.utcnow)
    user_id = db.Column(db.Integer, db.ForeignKey('users.id'))

    comments = db.relationship(
        'Comment',
        backref='post',
        lazy='dynamic'
    )

    def to_dict(self):
        data = {
            'id': self.id,
            'photo_url': self.photo_url,
            'author': self.author.username,
        }
        return data

#     def from_dict(self, data):
#         for field in ['caption', 'photo_url', 'author',
#                       'likes']:
#             if field in data:
#                 setattr(self, field, data[field])

src/app/posts/forms.py
from flask_wtf import FlaskForm
from flask_wtf.file import FileField, FileRequired, FileAllowed
from wtforms import StringField, SubmitField
from wtforms.validators import DataRequired
from wtforms.widgets import TextArea
from app import images


class UploadForm(FlaskForm):
    photo_description = StringField('Caption', validators=[DataRequired()],
                                    widget=TextArea())
    photo = FileField('Photo Upload', validators=[FileAllowed(images, 'Image Only!'),
                                                  FileRequired('Choose a file!')])
    submit = SubmitField('Upload')


class CommentForm(FlaskForm):
    body = StringField('Enter your comment', validators=[DataRequired()])
    submit = SubmitField('Submit')

src/app/main/__init__.py
from flask import Blueprint

main = Blueprint('main', __name__)

from app.main import views

src/app/main/views.py
from flask import render_template
from app.main import main


@main.route('/')
@main.route('/index')
def index():
    return render_template('main/index.html',
                           title='Main')

src/app/posts/__init__.py
from flask import Blueprint

posts = Blueprint('posts', __name__)

from app.posts import views

src/app/posts/views.py
import sys
import time
from flask import (
    current_app,
    flash,
    redirect,
    render_template,
    request,
    url_for,
)
from flask_login import current_user, login_required
from app.extensions import db, images
from app.posts import posts
from app.posts.forms import (
    CommentForm,
    UploadForm
)
from app.models import (
    Post,
    Comment,
)
from app import spaces, redis


@posts.before_request
@login_required
def require_login():
    pass


@posts.route('/')
def index():
    form = CommentForm()
    page = request.args.get('page', 1, type=int)
    posts = current_user.followed_posts().paginate(
        page, current_app.config['POSTS_PER_PAGE'], False)
    next_url = url_for('posts.index', page=posts.next_num) \
        if posts.has_next else None
    prev_url = url_for('posts.index', page=posts.prev_num) \
        if posts.has_prev else None
    if form.validate_on_submit():
        comment = Comment(body=form.body.data,
                          post=post,
                          author=current_user._get_current_object())
        db.session.add(comment)
        db.session.commit()

    return render_template('posts/index.html',
                           title='Followed Posts',
                           posts=posts.items,
                           form=form,
                           next_url=next_url,
                           prev_url=prev_url)


@posts.route('/favorites')
def favorites():
    form = CommentForm()
    page = request.args.get('page', 1, type=int)
    posts = current_user.liked_posts().paginate(
        page, current_app.config['POSTS_PER_PAGE'], False)
    next_url = url_for('posts.favorites', page=posts.next_num) \
        if posts.has_next else None
    prev_url = url_for('posts.favorites', page=posts.prev_num) \
        if posts.has_prev else None

    if form.validate_on_submit():
        comment = Comment(body=form.body.data,
                          post=post,
                          author=current_user._get_current_object())
        db.session.add(comment)
        db.session.commit()

    return render_template('posts/index.html',
                           title='Favorites',
                           posts=posts.items,
                           form=form,
                           next_url=next_url,
                           prev_url=prev_url)


@posts.route('/upload', methods=['GET', 'POST'])
def post():
    form = UploadForm()
    if form.validate_on_submit():
        file = request.files['photo']
        url = spaces.upload_file(file=file)
        post = Post(caption=form.photo_description.data,
                    photo_url=url,
                    author=current_user)
        db.session.add(post)
        db.session.commit()

        post_id = post.id
        user_id = current_user.id
        post_id_key = redis.POST_KEY_FORMAT.format(post_id)
        post_id_feed_key = redis.USER_FEED_KEY_FORMAT.format(user_id)
        post_id_user_key = redis.USER_POSTS_KEY_FORMAT.format(user_id)
        unix_time = int(time.time())

        followers = []
        for follower in current_user.get_my_following():
            followers.append(follower.id)

        with redis.r.pipeline() as pipe:
            pipe.multi()

            pipe.hmset(post_id_key,
                       {redis.POST_USERID_KEY: user_id,
                        redis.POST_UNIXTIME_KEY: unix_time,
                        redis.POST_BODY_KEY: post})

            pipe.lpush(post_id_feed_key, post_id)
            pipe.lpush(post_id_user_key, post_id)

            for follower in followers:
                post_id_follower_key = redis.USER_FEED_KEY_FORMAT.format(
                    follower)
                pipe.lpush(post_id_follower_key, post_id)

            pipe.lpush(redis.GENERAL_FEED_KEY, post_id)
            pipe.ltrim(redis.GENERAL_FEED_KEY, 0,
                       redis.GENERAL_FEED_MAX_POST_CNT - 1)

            pipe.execute()

        flash('Your post is now live!')
        return redirect(url_for('posts.index'))

    return render_template('posts/post.html',
                           title='Post',
                           form=form)


@posts.route('/details/<id>')
def details(id):
    post = Post.query.filter_by(id=id).first_or_404()
    form = CommentForm()
    if form.validate_on_submit():
        comment = Comment(body=form.body.data,
                          post=post,
                          author=current_user._get_current_object())
        db.session.add(comment)
        db.session.commit()
        flash('Your comment has been published.')
        return redirect(url_for('posts.index'))

    return render_template('posts/details.html',
                           title='Details',
                           form=form,
                           post=post)

src/app/templates/main/_post.html
<div class="post-item">

  <div class="Instagram-card">
    <div class="Instagram-card-header">
      <img class="Instagram-card-user-image" src="{{ post.author.profile_img_url or post.author.avatar(70) }}" style="height:50px;" />
      <a class="Instagram-card-user-name" href="{{ url_for('user.profile', username=post.author.username) }}">{{ post.author.username }}</a>
      <div class="Instagram-card-time">{{ moment(post.timestamp).fromNow() }}</div>
    </div>

    <div class="Instagram-card-image">
      <img id="post{{ post.id }}" src={{ post.photo_url }} height="400px">
    </div>

    <div class="Instagram-card-content">

      <div style="float:left;">
        <a class="footer-action-icons" href="#">
          <i class="fa fa-heart-o"></i>

          {% if current_user.has_liked(post) %}
            <form role="form">
              <div class="form-group">
                <button id="unlike-post" data-post-id={{ post.id }} type="submit" class="uk-button">Unlike</button>
              </div>
            </form>
          {% else %}
            <form role="form">
              <div class="form-group">
                <button id="like-post" data-post-id={{ post.id }} type="submit" class="uk-button">Like</button>
              </div>
            </form>
          {% endif %}
        </a>
      </div>

      <div class="Likes" style="float:left;">
        <div id = "likes" data-post-id={{ post.id }}>
          {% for like in post['likes'] %} 
            <a href="{{ url_for('user.profile', username=like.username) }}">{{ like.username }}</a>
          {% endfor %}
        </div>
      </div>

      <br>
      <br>
      <div>
        <a class="Instagram-card-content-user" href="{{ url_for('user.profile', username=post.author.username) }}">
          {{ post.author.username }}
          </a><span style="padding-left:10px">
          {{ post.caption }}<span>
      </div>
      {% include 'main/_comments.html' %}
    <hr>
    </div>  

    <div class="Instagram-card-footer">

      <div class="comment form">
        <form name="comment" data-post-id="{{post.id}}" action="{{ url_for('main.details', id=post.id) }}" method="POST">
          {{ form.hidden_tag() }}
            <div class="field">
              {{ form.body(class_="comments-input") }}
            </div>
          {{ form.submit }}
          {% for error in form.body.errors %}
            <li>{{ error }}</li>
          {% endfor %}
        </form>
      </div>

      <a class="footer-action-icons"href="#"><i class="fa fa-ellipsis-h"></i></a>
    </div>
  </div>
</div>
<br><br>

{% block js %}

  <script>
      $(document).ready(function() {
        $('form[name="comment"][data-post-id="{{ post.id }}"]').submit(function (e) {
          alert(JSON.stringify($('form[data-post-id="{{post.id}}"]').serialize()));
              $.ajax({
                  type: "POST",
                  url: "{{ url_for('api.comment', id=post.id) }}",
                data: $('form[data-post-id="{{ post.id }}"]').serialize(),
                  success: function (data) {
                     alert(JSON.stringify(data));
                     $('#comments[data-post-id="{{ post.id }}"]').append(" " +data.data)
                  },
                  error: function(xhr, ajaxOptions, thrownError){
                   alert('not_cool') 
                  },
              });
              e.preventDefault(); // block the traditional submission of the form.
          });
          $.ajaxSetup({
              beforeSend: function(xhr, settings) {
                  if (!/^(GET|HEAD|OPTIONS|TRACE)$/i.test(settings.type) && !this.crossDomain) {
                      xhr.setRequestHeader("X-CSRFToken", "{{ form.csrf_token._value() }}")
                  }
              }
          })
      });
  </script>

{% endblock %}

src/app/templates/main/_post_explore.html
<div class="grid-item">

  <table class = "ui celled padded table">
    <thead>
      <tr>
        <th class="single line">
          <img class="ui avatar image" 
            src="{{ post.author.profile_img_url or
            post.author.avatar(70) }}"
            style="height:70px;" />
          <span>
            {% set user_link %}
            <a href="{{ url_for('user.profile', username=post.author.username) }}">
              {{ post.author.username }}
            </a>
            {% endset %}
            {{ user_link }} said {{ moment(post.timestamp).fromNow() }}
            <br>
          </span>
        </th>
      </tr>
    </thead>
    <tbody>
      <tr>
      <td>
        <a id="open-modal" href="#modal-center" data-post-id="{{post.id}}"
          uk-toggle>
          <img id="post{{ post.id }}" src={{ post.photo_url }}
          style="height:150px;">
        </a>
        <br><br>
        {% if current_user.has_liked(post) %}
        <p><a class = "unlike_post{{ post.id }}" href="{{ url_for('api.unlike', id=post.id) }}">UnLike</a></p>
        {% else %}
        <p><a class = "like_post" data-post-id="{{ post.id }}" href="{{ url_for('api.like', id=post.id) }}"> Like</a></p>
        {% endif %}
        <div id = "likes" data-post-id={{ post.id }}>
          {% for like in post['likes'] %} {{ like.username }} {% endfor %}</div>
        <form role="form" id="like-post" data-post-id={{ post.id }}>
            <div class="form-group">
              <button id="like-send" type="submit" class="btn btn-primary">Like</button>
            </div>
        </form>
      </td>
      </tr>
    </tbody>
  </table>

  <div class="modal" id="modal_post{{post.id}}" data="{{post.id}}">
    <div class="modal-background"></div>
    <button class="modal-close is-large" aria-label="close"></button>
  </div>


  <div id="modal-center" class="uk-flex-top" uk-modal>
    <div class="uk-modal-dialog uk-modal-body uk-margin-auto-vertical">
      <div class="modal-content"></div>
      <button class="uk-modal-close-default" type="button" uk-close></button>
    </div>
  </div>

</div>

{% block js %}
  <script>
    document.querySelector('#open-modal[data-post-id="{{ post.id }}"]').addEventListener('click', function(event) {
    event.preventDefault();
    id=$(this).data('id')
    var modal = document.querySelector('.modal');
    var html = document.querySelector('html');
    modal.classList.add('is-active');
    html.classList.add('is-clipped');
    $.ajax({
      url: "{{ url_for('main.details', id=post.id )}}",
       type: "GET",
       success: function (data) {
         $(".modal-content").html(data);
       },
       error: function(xhr, ajaxOptions, thrownError){
        alert('not_cool')  //what to do in success
       },
    });
    modal.querySelector('.modal-background').addEventListener('click', function(e) {
      e.preventDefault();
      modal.classList.remove('is-active');
      html.classList.remove('is-clipped');
    });
  });
  </script>
  <script>
  $(document).ready(function () {
    $('#like-post[data-post-id="{{ post.id }}"]').submit(handleFormSubmit);
      function handleFormSubmit(evt) {
        postId = $(this).data('post-id');
        evt.preventDefault();
        addMessage(postId);
      }
      function addMessage() {
        $.ajax({
           url: "{{ url_for('api.like', id=post.id) }}",
           type: "GET",
           success: function (data) {
             $('#likes[data-post-id="{{ post.id }}"]').append(" " +data.data)
           },
           error: function(xhr, ajaxOptions, thrownError){
            alert('not_cool')  //what to do in success
           },
        });
      }
  });
  </script>
{% endblock %}

src/app/templates/main/_posts.html
<div id="posts">
  {% for post in posts %}
    {% include 'main/_post.html' %}
  {% endfor %}
</div>

src/app/templates/main/details.html
{% extends "base.html" %}

{% block app_content %}

  <table class = "ui celled padded table">
    <thead>
    <tr>
    <th class="single line">
      <img class="ui avatar image" src="{{ post.author.profile_img_url or
        post.author.avatar(70) }}"
        height="70px" />
      <span>
          {% set user_link %}
          <a href="{{ url_for('user.profile', username=post.author.username) }}">
            {{ post.author.username }}
          </a>
          {% endset %}
          {{ user_link }} said {{ moment(post.timestamp).fromNow() }}
          <br>
      </span>
    </th>
    </tr>
    </thead>
    <tbody>
      <tr>
      <td>
        <img id="post{{ post.id }}" src={{ post.photo_url }} height="400px">
         <br><br>
          {% if current_user.has_liked(post) %}
          <p><a class = "unlike_post{{ post.id }}" href="{{ url_for('api.unlike', id=post.id) }}">UnLike</a></p>
          {% else %}
          <p><a class = "like_post{{ post.id }}" href="{{ url_for('api.like', id=post.id) }}"> Like</a></p>
          {% endif %}
          {% for like in post['likes'] %} {{ like.username }} {% endfor %}

          <form role="form" id="like-post{{ post.id }}">
            <div class="form-group">
              <button id="like-send" type="submit" class="btn btn-primary">Like</button>
            </div>
          </form>

      </td>
      </tr>
    </tbody>
  </table>

  <div class="comment form">
    <h2>Leave a Comment</h2> 
    <form  data-post-id="{{post.id}}" action="{{ url_for('main.details', id=post.id) }}" method="POST">
      {{ form.hidden_tag() }}
        <div class="field">
          {{ form.body.label }}
          {{ form.body}}
        </div>
      {{ form.submit }}
      {% for error in form.body.errors %}
        <li>{{ error }}</li>
      {% endfor %}
    </form>
  </div>

  {% include 'main/_comments.html' %}

{% endblock %}

{% block js %}
  <script>
      $(document).ready(function() {
        $('form[data-post-id="{{ post.id }}"]').submit(function (e) {
          alert(JSON.stringify($('form[data-post-id="{{post.id}}"]').serialize()));
              $.ajax({
                  type: "POST",
                  url: "{{ url_for('api.comment', id=post.id) }}",
                data: $('form[data-post-id="{{ post.id }}"]').serialize(),
                  success: function (data) {
                     alert(JSON.stringify(data));
                     $('#comments[data-post-id="{{ post.id }}"]').append(" " +data.data)
                  },
                  error: function(xhr, ajaxOptions, thrownError){
                   alert('not_cool') 
                  },
              });
              e.preventDefault(); // block the traditional submission of the form.
          });
          $.ajaxSetup({
              beforeSend: function(xhr, settings) {
                  if (!/^(GET|HEAD|OPTIONS|TRACE)$/i.test(settings.type) && !this.crossDomain) {
                      xhr.setRequestHeader("X-CSRFToken", "{{ form.csrf_token._value() }}")
                  }
              }
          })
      });
  </script>
{% endblock %}

src/app/templates/main/edit_profile.html
{% extends "base.html" %}

{% block app_content %}
<main class="ui text container">

  <h2 class="ui header">
    <div class="content">
      Edit Profile
    </div>
  </h2>

  <form action="{{ url_for('main.edit_profile') }}" method="POST" enctype="multipart/form-data">
    <div class="ui segment">
        {{ form.hidden_tag() }}
        <div class="field">
          {{ form.username.label }}<br>
          {{ form.username(size=32) }}<br>
          {% for error in form.username.errors %}
            <span style="color: red;">[{{ error }}]</span>
          {% endfor %}
        </div>
        <div class="field">
          {{ form.bio.label }}<br>
          {{ form.bio(cols=50, rows=4) }}<br>
          {% for error in form.bio.errors %}
            <span style="color: red;">[{{ error }}]</span>
          {% endfor %}
        </div>
        <div class="field">
          {{ form.profile_img.label }}
          {{ form.profile_img }}
        </div>
      {{ form.submit(class="ui submit button") }}
    </form>
</main>
{% endblock %}

src/app/templates/main/explore.html
{% extends "base.html" %}

{% block app_content %}
  <main class="ui text container">
    <div class="post photo">
      <h2>Photos</h2> 

        <div class="grid">
          {% include 'main/_posts_explore.html' %}
        </div>

    </div>
  </main>
{% endblock %}

{% block js %}
<script src="https://unpkg.com/masonry-layout@4/dist/masonry.pkgd.js"></script>
<script src="https://unpkg.com/imagesloaded@4/imagesloaded.pkgd.min.js"></script>

<script>
var $grid = $('.grid').masonry({
  itemSelector: '.grid-item',
  columnWidth: 150
});
$grid.imagesLoaded().progress( function() {
  $grid.masonry('layout');
});
</script>

{% endblock %}

src/app/templates/main/followers.html
  {% for follower in followers %}
  <table class = "ui celled padded table">
    <thead>
      <tr>
        <th class="single line">
          <img class="ui avatar image" 
            src="{{ follower.profile_img_url or
            follower.avatar(70) }}"
            height="70px" />
          <span>
            <a href="{{ url_for('main.user', username=follower.username) }}">
              {{ follower.username }}
            </a>
            <br>
          </span>
        </th>
      </tr>
    </thead>
    <tbody>
      <tr>
      <td>
        <br><br>
      </td>
      </tr>
    </tbody>
  </table>

    {% endfor %}

src/app/templates/main/following.html
  {% for followee in following %}
  <table class = "ui celled padded table">
    <thead>
      <tr>
        <th class="single line">
          <img class="ui avatar image" 
            src="{{ followee.profile_img_url or
            followee.avatar(70) }}"
            height="70px" />
          <span>
            <a href="{{ url_for('main.user', username=followee.username) }}">
              {{ followee.username }}
            </a>
            <br>
          </span>
        </th>
      </tr>
    </thead>
    <tbody>
      <tr>
      <td>
        <br><br>
      </td>
      </tr>
    </tbody>
  </table>

    {% endfor %}

src/app/templates/main/index.html
{% extends "base.html" %}

{% block main_content %}

<div class="home-container">
  <div class="content"></div>
    <div class="message">
      <div class="uk-container">
        <h1 class = "uk-heading-primary">Filmogram</h1>    
        <p>Yours to discover</p>    
        <a class="uk-button uk-button-large uk-button-default"
          href="{{ url_for('account.register') }}">Register</a>
        <a class="uk-button uk-button-large uk-button-default"
          href="{{ url_for('account.login') }}">Login</a>
      </div>
    </div>
</div>
{% endblock %}

src/app/templates/main/post.html
{% extends "base.html" %}

{% block app_content %}

  <main class="ui text container">
  
    <form class = "mui-form" action="{{ url_for('main.post') }}" method="POST" enctype="multipart/form-data">
    <fieldset class="uk-fieldset">
    <legend class="uk-legend">Add a Photo</legend> 
      {{ form.hidden_tag() }}

        <img id="target" src="http://placehold.it/180" alt="your image" />

        <div class="uk-margin">
          <div uk-form-custom>
            {{ form.photo(class_="imgInp uk-input") }}
            <button class="uk-button" type="button"
              tabindex="-1">Upload Photo</button>
          </div>
        </div>

        <div class="uk-margin">
          {{ form.photo_description.label }}
          {{ form.photo_description(class_="uk-textarea") }}
        </div>

      {{ form.submit(class_="uk-button uk-button-default") }}

      {% for error in form.photo_description.errors %}
        <li>{{ error }}</li>
      {% endfor %}

    </fieldset>
    </form>
  {% if success %}
  <br>
  <p>Post Success!</p>
  {% endif %}
  </main>
 
{% endblock %}

  {% block js %}
  <script>
   function readURL(input) {
     if (input.files && input.files[0]) {
       var reader = new FileReader();
       reader.onload = function (e) {
         $('#target')
           .attr('src', e.target.result);
       };
       reader.readAsDataURL(input.files[0]);
     }
   }
  $(".imgInp").change(function(){
    readURL(this);
  })
  ;
  </script>
  {% endblock %}

src/app/templates/main/profile.html
{% extends "base.html" %}

{% block app_content %}
<main class="ui container">

  <div class="ui items">
    <div class="item">

      <div class="image">
        {% if user.profile_img_url %}
          <img src="{{ user.profile_img_url }}" style="width:256px;height:256px;">
        {% else %}
          <img src="{{ user.avatar(256) }}">
        {% endif %}
      </div>

      <div class="content">

        <div class="header">{{ user.username }}</div>

        <div class="meta">
          <p>
            <p><span> {{ user.followers.count() }}<a href="{{ url_for('main.followers', username=user.username) }}">
               Followers</a></p>
            <p><span> {{ user.followed.count() }}<a href="{{
                  url_for('main.following', username=user.username) }}">
               Following</a></p>
          </p>
        </div>

        <div class="description">
          {% if user.bio %}
            <p>{{ user.bio }}</p>
          {% endif %}
        </div>

        {% if user == current_user %}
          <p><a href="{{ url_for('main.edit_profile') }}">Edit your profile</a></p>
        {% elif not current_user.is_following(user) %}
          <p><a href="{{ url_for('api.follow', username=user.username) }}"> Follow</a></p>
        {% else %}
          <p><a href="{{ url_for('api.unfollow', username=user.username) }}">Unfollow</a></p>
        {% endif %}
        <form role="form" id="follow-user" data-username="{{
          user.username}}">
            <div class="form-group">
              <button id="user-send" type="submit" class="btn
                btn-primary">Follow</button>
            </div>
        </form>

      </div>
    </div>
  </div>

  {% for post in posts %}
      {% include 'main/_post.html' %}
  {% endfor %}

</main>
{% endblock %}

{% block js %}
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.0/jquery.min.js"></script>

  <script>
  $(document).ready(function () {
    $("#follow-user").submit(handleFormSubmit);

      function handleFormSubmit(evt) {
        username = $(this).data('username');
        evt.preventDefault();
        addMessage(username);
      }

      function addMessage(username) {
        $.ajax({
           url: "/api/follow/"+username,
           type: "GET",
           success: function (data) {
            alert('cool')  
           },
           error: function(xhr, ajaxOptions, thrownError){
            alert('not_cool') 
           },
        });
      }
  });
  </script>

{% endblock %}

src/app/templates/main/upload.html
{% extends "base.html" %}

{% block app_content %}

  <main class="ui text container">

  <div class="upload photo">
    <h2>Add a Photo</h2> 
    <form action="{{ url_for('main.upload') }}" method="POST" enctype="multipart/form-data">
      {{ form.hidden_tag() }}
        <div class="field">
          {{ form.photo_description.label }}
          {{ form.photo_description }}
        </div>
        <img id="target" src="http://placehold.it/180" alt="your image" />
        <div class="field">
          {{ form.photo.label }}
          {{ form.photo(class_="imgInp") }}
        </div>
      {{ form.submit }}
      {% for error in form.photo_description.errors %}
        <li>{{ error }}</li>
      {% endfor %}
    </form>
  </div>
  {% if success %}
  <br>
  <p>Upload Success!</p>
  {% endif %}
  </main>
 
  {% block js %}
  <script>
   function readURL(input) {
     if (input.files && input.files[0]) {
       var reader = new FileReader();
       reader.onload = function (e) {
         $('#target')
           .attr('src', e.target.result);
       };
       reader.readAsDataURL(input.files[0]);
     }
   }

  $(".imgInp").change(function(){
    readURL(this);
  })
  ;
  </script>
  {% endblock %}

{% endblock %}