src/app/models/comment.py
from app.extensions import db
from datetime import datetime


class Comment(db.Model):
    __tablename__ = 'comments'

    id = db.Column(db.Integer, primary_key=True)
    body = db.Column(db.String(140))
    timestamp = db.Column(db.DateTime, index=True, default=datetime.utcnow)
    user_id = db.Column(db.Integer, db.ForeignKey('users.id'))
    post_id = db.Column(db.Integer, db.ForeignKey('posts.id',
                                                  ondelete='CASCADE'))

src/app/models/post.py
from app.extensions import db
from datetime import datetime


class Post(db.Model):
    __tablename__ = 'posts'

    id = db.Column(db.Integer, primary_key=True)
    caption = db.Column(db.String(140), nullable=True)
    photo_url = db.Column(db.String)
    timestamp = db.Column(db.DateTime, index=True, default=datetime.utcnow)
    user_id = db.Column(db.Integer, db.ForeignKey('users.id'))

    comments = db.relationship(
        'Comment',
        backref='post',
        lazy='dynamic'
    )

    def to_dict(self):
        data = {
            'id': self.id,
            'photo_url': self.photo_url,
            'author': self.author.username,
        }
        return data

#     def from_dict(self, data):
#         for field in ['caption', 'photo_url', 'author',
#                       'likes']:
#             if field in data:
#                 setattr(self, field, data[field])

src/app/posts/forms.py
from flask_wtf import FlaskForm
from flask_wtf.file import FileField, FileRequired, FileAllowed
from wtforms import StringField, SubmitField
from wtforms.validators import DataRequired
from wtforms.widgets import TextArea
from app import images


class UploadForm(FlaskForm):
    photo_description = StringField('Caption', validators=[DataRequired()],
                                    widget=TextArea())
    photo = FileField('Photo Upload', validators=[FileAllowed(images, 'Image Only!'),
                                                  FileRequired('Choose a file!')])
    submit = SubmitField('Upload')


class CommentForm(FlaskForm):
    body = StringField('Enter your comment', validators=[DataRequired()])
    submit = SubmitField('Submit')

src/app/posts/__init__.py
from flask import Blueprint

posts = Blueprint('posts', __name__)

from app.posts import views

src/app/posts/views.py
import sys
import time
from flask import (
    current_app,
    flash,
    redirect,
    render_template,
    request,
    url_for,
)
from flask_login import current_user, login_required
from app.extensions import db, images
from app.posts import posts
from app.posts.forms import (
    CommentForm,
    UploadForm
)
from app.models import (
    Post,
    Comment,
)
from app import spaces, redis


@posts.before_request
@login_required
def require_login():
    pass


@posts.route('/')
def index():
    form = CommentForm()
    page = request.args.get('page', 1, type=int)
    posts = current_user.followed_posts().paginate(
        page, current_app.config['POSTS_PER_PAGE'], False)
    next_url = url_for('posts.index', page=posts.next_num) \
        if posts.has_next else None
    prev_url = url_for('posts.index', page=posts.prev_num) \
        if posts.has_prev else None
    if form.validate_on_submit():
        comment = Comment(body=form.body.data,
                          post=post,
                          author=current_user._get_current_object())
        db.session.add(comment)
        db.session.commit()

    return render_template('posts/index.html',
                           title='Followed Posts',
                           posts=posts.items,
                           form=form,
                           next_url=next_url,
                           prev_url=prev_url)


@posts.route('/favorites')
def favorites():
    form = CommentForm()
    page = request.args.get('page', 1, type=int)
    posts = current_user.liked_posts().paginate(
        page, current_app.config['POSTS_PER_PAGE'], False)
    next_url = url_for('posts.favorites', page=posts.next_num) \
        if posts.has_next else None
    prev_url = url_for('posts.favorites', page=posts.prev_num) \
        if posts.has_prev else None

    if form.validate_on_submit():
        comment = Comment(body=form.body.data,
                          post=post,
                          author=current_user._get_current_object())
        db.session.add(comment)
        db.session.commit()

    return render_template('posts/index.html',
                           title='Favorites',
                           posts=posts.items,
                           form=form,
                           next_url=next_url,
                           prev_url=prev_url)


@posts.route('/upload', methods=['GET', 'POST'])
def post():
    form = UploadForm()
    if form.validate_on_submit():
        file = request.files['photo']
        url = spaces.upload_file(file=file)
        post = Post(caption=form.photo_description.data,
                    photo_url=url,
                    author=current_user)
        db.session.add(post)
        db.session.commit()

        post_id = post.id
        user_id = current_user.id
        post_id_key = redis.POST_KEY_FORMAT.format(post_id)
        post_id_feed_key = redis.USER_FEED_KEY_FORMAT.format(user_id)
        post_id_user_key = redis.USER_POSTS_KEY_FORMAT.format(user_id)
        unix_time = int(time.time())

        followers = []
        for follower in current_user.get_my_following():
            followers.append(follower.id)

        with redis.r.pipeline() as pipe:
            pipe.multi()

            pipe.hmset(post_id_key,
                       {redis.POST_USERID_KEY: user_id,
                        redis.POST_UNIXTIME_KEY: unix_time,
                        redis.POST_BODY_KEY: post})

            pipe.lpush(post_id_feed_key, post_id)
            pipe.lpush(post_id_user_key, post_id)

            for follower in followers:
                post_id_follower_key = redis.USER_FEED_KEY_FORMAT.format(
                    follower)
                pipe.lpush(post_id_follower_key, post_id)

            pipe.lpush(redis.GENERAL_FEED_KEY, post_id)
            pipe.ltrim(redis.GENERAL_FEED_KEY, 0,
                       redis.GENERAL_FEED_MAX_POST_CNT - 1)

            pipe.execute()

        flash('Your post is now live!')
        return redirect(url_for('posts.index'))

    return render_template('posts/post.html',
                           title='Post',
                           form=form)


@posts.route('/details/<id>')
def details(id):
    post = Post.query.filter_by(id=id).first_or_404()
    form = CommentForm()
    if form.validate_on_submit():
        comment = Comment(body=form.body.data,
                          post=post,
                          author=current_user._get_current_object())
        db.session.add(comment)
        db.session.commit()
        flash('Your comment has been published.')
        return redirect(url_for('posts.index'))

    return render_template('posts/details.html',
                           title='Details',
                           form=form,
                           post=post)

src/app/templates/posts/_comments.html
<div class = "comments" >
  <div data-post-id = "{{post.id}}">
    <ul class="uk-list">
    {% for comment in post['comments'] %} 
      <li>
        <a class="social-card-content-user" href="{{ url_for('users.profile', username=comment.author.username) }}">
          {{ comment.author.username }}
        </a>
        <span style="padding-left:10px"> {{comment.body}} </span></br>
      </li>
    {% endfor %}
    <ul>
  </div>
</div>

src/app/templates/posts/_post.html
<div class="post-item">

  <div class="social-card">
    <div class="social-card-header">
      <img class="social-card-user-image" src="{{
      post.author.profile_img_url or post.author.avatar(70) }}" />
      <a class="social-card-user-name" href="{{ url_for('users.profile', username=post.author.username) }}">{{ post.author.username }}</a>
      <div class="social-card-time">{{ moment(post.timestamp).fromNow() }}</div>
    </div>

    <div class="social-card-image">
      <img id="post" data-post-id="{{ post.id}}" src={{ post.photo_url }} height="400px">
    </div>

    <div class="social-card-content">
      <div style="float:left; padding-right:10px;">
          {% if current_user.has_liked(post) %}
          <button class="uk-button uk-button-small uk-button-primary js-toggle-like"
            type="button" data-post-id={{ post.id }} uk-icon="check">
          </button>
          {% else %}
          <button class="uk-button uk-button-small uk-button-default js-toggle-like" 
            type="button" data-post-id={{ post.id }} uk-icon="check">
          </button>
          {% endif %}
      </div>

      <div class = "likes" >
        <div id = "likes" data-post-id={{ post.id }}>
          {% for like in post['likes'] %} 
            <a href="{{ url_for('users.profile', username=like.username) }}"
              class='uk-link-text'>{{ like.username }}</a>
          {% endfor %}
        </div>
      </div>

      <br><br>

      <div style = "padding-bottom: 5px;">
        <a class="social-card-content-user" href="{{ url_for('users.profile', username=post.author.username) }}">
          {{ post.author.username }}
          </a><span style="padding-left:10px">
          {{ post.caption }}<span>
      </div>
      {% include 'posts/_comments.html' %}
    <hr>
    </div>  

    <div class="social-card-footer">
      <div style="box-sizing: border-box; width:100%;">
        <form name="comment" data-post-id="{{post.id}}" class="js-comment"  action="{{
          url_for('posts.details', id=post.id) }}" method="POST">
          <fieldset class="uk-fieldset">
            {{ form.hidden_tag() }}
              <div class="uk-margin">
                {{ form.body(class_="comments-input uk-textarea") }}
                {{ form.submit(class_="uk-button uk-button-default") }}
              </div>
            {% for error in form.body.errors %}
              <span class="uk-text-danger">{{ error }}</span>
            {% endfor %}
          </fieldset>
        </form>
      </div>
      <a class="footer-action-icons"href="#"><i class="fa fa-ellipsis-h"></i></a>
    </div>
  </div>
</div>
<br><br>

src/app/templates/posts/_posts.html
<div id = 'posts'>
  {% for post in posts %}
    {% include 'posts/_post.html' %}
  {% endfor %}
</div>

src/app/templates/posts/details.html
{% extends "base.html" %}

{% block app_content %}

  <table class = "ui celled padded table">
    <thead>
    <tr>
    <th class="single line">
      <img class="ui avatar image" src="{{ post.author.profile_img_url or
        post.author.avatar(70) }}"
        height="70px" />
      <span>
        {% set user_link %}
        <a href="{{ url_for('user.profile', username=post.author.username) }}">
          {{ post.author.username }}
        </a>
        {% endset %}
        {{ user_link }} said {{ moment(post.timestamp).fromNow() }}
        <br>
      </span>
    </th>
    </tr>
    </thead>
    <tbody>
      <tr>
      <td>
        <img id="post{{ post.id }}" src={{ post.photo_url }} height="400px">
        <br><br>
        {% if current_user.has_liked(post) %}
        <p><a class = "unlike_post{{ post.id }}" href="{{ url_for('api.unlike', id=post.id) }}">UnLike</a></p>
        {% else %}
        <p><a class = "like_post{{ post.id }}" href="{{ url_for('api.like', id=post.id) }}"> Like</a></p>
        {% endif %}
        {% for like in post['likes'] %} {{ like.username }} {% endfor %}
        <form role="form" id="like-post{{ post.id }}">
          <div class="form-group">
            <button id="like-send" type="submit" class="btn btn-primary">Like</button>
          </div>
        </form>
      </td>
      </tr>
    </tbody>
  </table>

  <div class="comment form">
    <h2>Leave a Comment</h2> 
    <form  data-post-id="{{post.id}}" action="{{ url_for('posts.details', id=post.id) }}" method="POST">
      {{ form.hidden_tag() }}
        <div class="field">
          {{ form.body.label }}
          {{ form.body}}
        </div>
      {{ form.submit }}
      {% for error in form.body.errors %}
        <li>{{ error }}</li>
      {% endfor %}
    </form>
  </div>

  {% include 'explore/_comments.html' %}
{% endblock %}

{% block js %}
  <script>
      $(document).ready(function() {
        $('form[data-post-id="{{ post.id }}"]').submit(function (e) {
          alert(JSON.stringify($('form[data-post-id="{{post.id}}"]').serialize()));
              $.ajax({
                  type: "POST",
                  url: "{{ url_for('api.comment', id=post.id) }}",
                data: $('form[data-post-id="{{ post.id }}"]').serialize(),
                  success: function (data) {
                     alert(JSON.stringify(data));
                     $('#comments[data-post-id="{{ post.id }}"]').append(" " +data.data)
                  },
                  error: function(xhr, ajaxOptions, thrownError){
                   alert('not_cool') 
                  },
              });
              e.preventDefault(); // block the traditional submission of the form.
          });
          $.ajaxSetup({
              beforeSend: function(xhr, settings) {
                  if (!/^(GET|HEAD|OPTIONS|TRACE)$/i.test(settings.type) && !this.crossDomain) {
                      xhr.setRequestHeader("X-CSRFToken", "{{ form.csrf_token._value() }}")
                  }
              }
          })
      });
  </script>
{% endblock %}

src/app/templates/posts/index.html
{% extends "base.html" %}

{% block app_content %}
<main class="uk-container">
  {% if posts %}
    <h1 class="uk-heading-line"><span>Photos</span></h1>
      <div>
        {% include 'posts/_posts.html' %}
        {% if next_url %}
          <a class="npage" hidden href={{ next_url or "#" }}>next_url</a>
        {% endif %}
      </div>
  {% else %}
    <p> No posts!</p>
  {% endif %}
</main>
{% endblock %}

src/app/templates/posts/post.html
{% extends "base.html" %}

{% block app_content %}

<main class="uk-container">
<h1 class="uk-heading-line"><span>Upload A Photo</span></h1>
  <div class="uk-card uk-card-default uk-card-body">
    <form action="{{ url_for('posts.post') }}" method="POST" enctype="multipart/form-data">
      <fieldset class="uk-fieldset">

        {{ form.hidden_tag() }}
        <div class="uk-card-body">
          <img id="target" src="http://placehold.it/500x300" alt="your image" />
          <div class="uk-margin">
            <div uk-form-custom>
              {{ form.photo(class_="imgInp uk-input") }}
              <button class="uk-button" type="button" tabindex="-1">Upload Photo</button>
            </div>
          </div>
          <div class="uk-margin">
            {{ form.photo_description(class_="uk-textarea", placeholder="Caption") }}
          </div>
          {% for error in form.photo_description.errors %}
            <span class="uk-text-danger">{{ error }}</span>
          {% endfor %}
          {{ form.submit(class_="uk-button uk-button-default") }}
        </div>

      </fieldset>
    </form>
  </div>
</main>
 
<footer>
  <div class="uk-container">
    <div class="uk-padding"></div>
    </div>
  </div>
</footer>

{% endblock %}