src/app/models/user.py
import jwt
import sys
import json
from app.extensions import db
from datetime import datetime
from hashlib import md5
from flask_login import AnonymousUserMixin, UserMixin
from app.extensions import bcrypt, login
from app.models.post import Post
from app.models.notification import Notification
from app.models.user_notification import UserNotification

likes = db.Table(
    'likes',
    db.Column('user_id', db.Integer, db.ForeignKey('users.id')),
    db.Column('post_id', db.Integer, db.ForeignKey('posts.id',
                                                   ondelete='CASCADE'))
)

followers = db.Table(
    'followers',
    db.Column('follower_id', db.Integer, db.ForeignKey('users.id')),
    db.Column('followed_id', db.Integer, db.ForeignKey('users.id'))
)


class User(UserMixin, db.Model):
    __tablename__ = 'users'

    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String(64), index=True,
                         unique=True, nullable=False)
    email = db.Column(db.String(120), index=True, unique=True, nullable=False)
    password = db.Column(db.Binary(128), nullable=True)
    bio = db.Column(db.String(140))
    profile_img_url = db.Column(db.String)
    last_user_notification_read_time = db.Column(db.DateTime)
    role_id = db.Column(db.Integer, db.ForeignKey('roles.id'))

    posts = db.relationship(
        'Post',
        backref='author',
        lazy='dynamic'
    )
    followed = db.relationship(
        'User',
        secondary=followers,
        primaryjoin=(followers.c.follower_id == id),
        secondaryjoin=(followers.c.followed_id == id),
        backref=db.backref('followers', lazy='joined'),
        lazy='dynamic'
    )
    likes = db.relationship(
        'Post',
        secondary=likes,
        primaryjoin=(likes.c.user_id == id),
        backref=db.backref('likes', lazy='joined'),
        lazy='dynamic'
    )
    comments = db.relationship(
        'Comment',
        backref='author',
        lazy='dynamic'
    )
    notifications = db.relationship(
        'Notification',
        backref='user',
        lazy='dynamic'
    )
    user_notification_sent = db.relationship(
        'UserNotification',
        foreign_keys='UserNotification.sender_id',
        backref='author',
        lazy='dynamic'
    )
    user_notification_received = db.relationship(
        'UserNotification',
        foreign_keys='UserNotification.recipient_id',
        backref='recipient',
        lazy='dynamic'
    )

    def __init__(self, username, email, role=None, password=None, **kwargs):
        super(User, self).__init__(**kwargs)
        if role:
            self.role = role
        db.Model.__init__(self, username=username, email=email, **kwargs)
        if password:
            self.set_password(password)
        else:
            self.password = None

    def set_password(self, password):
        self.password = bcrypt.generate_password_hash(password)

    def check_password(self, value):
        return bcrypt.check_password_hash(self.password, value)

    def avatar(self, size):
        digest = md5(self.email.lower().encode('utf-8')).hexdigest()
        return 'https://www.gravatar.com/avatar/{}?d=identicon&s={}'.format(
            digest, size)

    def follow(self, user):
        if not self.is_following(user):
            self.followed.append(user)

    def unfollow(self, user):
        if self.is_following(user):
            self.followed.remove(user)

    def is_following(self, user):
        if self.followed:
            return self.followed.filter(
                followers.c.followed_id == user.id).count() > 0

    def followed_posts(self):
        followed = Post.query.join(
            followers,
            (followers.c.followed_id == Post.user_id)).filter(
                followers.c.follower_id == self.id)
        own = Post.query.filter_by(user_id=self.id)
        return followed.union(own).order_by(Post.timestamp.desc())

    def like(self, post):
        if not self.has_liked(post):
            self.likes.append(post)

    def unlike(self, post):
        if self.has_liked(post):
            self.likes.remove(post)

    def has_liked(self, post):
        if self.likes:
            return self.likes.filter(
                likes.c.post_id == post.id).count() > 0

    def liked_posts(self):
        liked = Post.query.join(
            likes,
            (likes.c.post_id == Post.id)) \
            .filter(
            likes.c.user_id == self.id)
        return liked.order_by(Post.timestamp.desc())

    def new_messages(self):
        last_read_time = self.last_user_notification_read_time or datetime(
            1900, 1, 1)
        return UserNotification.query.filter_by(recipient=self).filter(
            UserNotification.timestamp > last_read_time).count()

    def add_notification(self, name, data):
        if self.notifications:
            self.notifications.filter_by(name=name).delete()
            n = Notification(
                name=name, payload_json=json.dumps(data), user=self)
            db.session.add(n)
            return n

    def get_my_following(self):
        my_following = self.query.join(
            followers,
            (followers.c.followed_id == User.id)) \
            .filter(followers.c.follower_id == self.id)
        return my_following

    def get_my_followers(self):
        my_followers = self.query.join(
            followers,
            (followers.c.follower_id == User.id)) \
            .filter(followers.c.followed_id == self.id)
        return my_followers

    @property
    def follower_count(self):
        if self.followers:
            return len(self.followers)
        return 0

    @property
    def followed_count(self):
        if self.followed and self.followed.all():
            return len(self.followed.all())
        return 0

    def can(self, permissions):
        return self.role.permissions >= permissions

    def is_demo_admin(self):
        return self.can(Permission.DEMO_ADMINISTER)

    def is_admin(self):
        return self.can(Permission.ADMINISTER)


class AnonymousUser(AnonymousUserMixin):
    def can(self, _):
        return False

    def is_admin(self):
        return False

    def is_demo_admin(self):
        return False


class Permission:
    GENERAL = 0
    DEMO_ADMINISTER = 1
    ADMINISTER = 2


class Role(db.Model):
    __tablename__ = 'roles'

    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(64), unique=True)
    index = db.Column(db.String(64))
    default = db.Column(db.Boolean, default=False, index=True)
    permissions = db.Column(db.Integer)
    users = db.relationship('User', backref='role', lazy='dynamic')

    @staticmethod
    def insert_roles():
        roles = {
            'User': (Permission.GENERAL, 'main', True),
            'DemoAdministrator': (Permission.DEMO_ADMINISTER, 'demo_admin', False),
            'Administrator': (Permission.ADMINISTER, 'admin', False)
        }
        for r in roles:
            role = Role.query.filter_by(name=r).first()
            if role is None:
                role = Role(name=r)
            role.permissions = roles[r][0]
            role.index = roles[r][1]
            role.default = roles[r][2]
            db.session.add(role)
        db.session.commit()


class AnonymousUser(AnonymousUserMixin):
    def can(self, _):
        return False

    def is_admin(self):
        return False

    def is_demo_admin(self):
        return False


@login.user_loader
def load_user(id):
    return User.query.get(int(id))

src/app/users/forms.py
from flask_wtf import FlaskForm
from flask_wtf.file import FileField, FileRequired, FileAllowed
from wtforms import StringField, TextAreaField, SubmitField
from wtforms.validators import DataRequired, Length, ValidationError
from app.models import User
from app import images


class EditProfileForm(FlaskForm):
    username = StringField('Username', validators=[DataRequired()])
    bio = TextAreaField('About me', validators=[Length(min=0, max=140)])
    profile_img = FileField('Photo Upload', validators=[FileAllowed(
        images, 'Image Only!')])
    submit = SubmitField('Submit')

    def __init__(self, original_username, *args, **kwargs):
        super(EditProfileForm, self).__init__(*args, **kwargs)
        self.original_username = original_username

    def validate_username(self, username):
        if username.data != self.original_username:
            user = User.query.filter_by(username=self.username.data).first()
            if user is not None:
                raise ValidationError('Please use a different username.')


class CommentForm(FlaskForm):
    body = StringField('Enter your comment', validators=[DataRequired()])
    submit = SubmitField('Submit')

src/app/user/views.py
import sys
from flask import (
    current_app,
    render_template,
    redirect,
    request,
    flash,
    url_for,
)
from flask_login import current_user, login_required
from app.extensions import db, images
from app.user import user
from app.user.forms import (
    CommentForm,
    EditProfileForm
)
from app.models import (
    Post,
    User,
    Comment,
)


@user.route('/<username>')
def profile(username):
    form = CommentForm()
    user = User.query.filter_by(username=username).first_or_404()
    page = request.args.get('page', 1, type=int)
    posts = user.posts.order_by(Post.timestamp.desc()).paginate(
        page, current_app.config['POSTS_PER_PAGE'], False)
    following = user.get_my_following()
    followers = user.get_my_followers()
    next_url = url_for('user.profile', username=user.username,
                       page=posts.next_num) if posts.has_next else None
    prev_url = url_for('user.profile', username=user.username,
                       page=posts.prev_num) if posts.has_prev else None
    if form.validate_on_submit():
        comment = Comment(body=form.body.data,
                          # post=post,
                          author=current_user._get_current_object())
        db.session.add(comment)
        db.session.commit()

    return render_template('user/profile.html',
                           title='User',
                           user=user,
                           followers=followers,
                           following=following,
                           form=form,
                           posts=posts.items,
                           next_url=next_url,
                           prev_url=prev_url)


@user.route('/edit_profile', methods=['GET', 'POST'])
@login_required
def edit_profile():
    form = EditProfileForm(current_user.username)
    print('hi')
    if form.validate_on_submit():
        if request.files['profile_img']:
            file = request.files['profile_img']
            filename = images.save(file)
            url = images.url(filename)
            current_user.profile_img_url = url
        current_user.username = form.username.data
        current_user.bio = form.bio.data
        db.session.commit()
        print('aobut to save')
        flash('Your changes have been saved.')
        return redirect(url_for('user.profile', username=current_user.username))
    elif request.method == 'GET':
        form.username.data = current_user.username
        form.bio.data = current_user.bio

    return render_template('user/edit_profile.html',
                           title='Edit Profile',
                           form=form)


@user.route('/discover/')
def discover():
    users = User.query.all()

    return render_template('user/discover.html',
                           title='Discover',
                           users=users)

src/app/users/__init__.py
from flask import Blueprint

users = Blueprint('users', __name__)

from app.users import views

src/app/users/views.py
import sys
from flask import (
    current_app,
    render_template,
    redirect,
    request,
    flash,
    url_for,
)
from flask_login import current_user, login_required
from app.extensions import db, images
from app.users import users
from app.users.forms import (
    CommentForm,
    EditProfileForm
)
from app.models import (
    Post,
    User,
    Comment,
)
from app import spaces


@users.before_request
@login_required
def require_login():
    pass


@users.route('/')
def discover():
    users = User.query.all()

    return render_template('user/discover.html',
                           title='Discover',
                           users=users)


@users.route('/<username>')
def profile(username):
    form = CommentForm()
    user = User.query.filter_by(username=username).first_or_404()
    page = request.args.get('page', 1, type=int)
    posts = user.posts.order_by(Post.timestamp.desc()).paginate(
        page, current_app.config['POSTS_PER_PAGE'], False)
    following = user.get_my_following()
    followers = user.get_my_followers()
    next_url = url_for('users.profile', username=user.username,
                       page=posts.next_num) if posts.has_next else None
    prev_url = url_for('users.profile', username=user.username,
                       page=posts.prev_num) if posts.has_prev else None
    if form.validate_on_submit():
        comment = Comment(body=form.body.data,
                          # post=post,
                          author=current_user._get_current_object())
        db.session.add(comment)
        db.session.commit()

    return render_template('user/profile.html',
                           title='User',
                           user=user,
                           followers=followers,
                           following=following,
                           form=form,
                           posts=posts.items,
                           next_url=next_url,
                           prev_url=prev_url)


@users.route('/edit_profile', methods=['GET', 'POST'])
def edit_profile():
    form = EditProfileForm(current_user.username)
    if form.validate_on_submit():
        if request.files['profile_img']:
            file = request.files['profile_img']
            url = spaces.upload_file(file=file)
            current_user.profile_img_url = url
        current_user.username = form.username.data
        current_user.bio = form.bio.data
        db.session.commit()
        flash('Your changes have been saved.')
        return redirect(url_for('users.profile', username=current_user.username))
    elif request.method == 'GET':
        form.username.data = current_user.username
        form.bio.data = current_user.bio

    return render_template('user/edit_profile.html',
                           title='Edit Profile',
                           form=form)

src/app/templates/user/_followers.html
<div id="followers">
  <div class="uk-search uk-search-default">
    <span uk-search-icon></span>
    <input class="search uk-search-input" placeholder="Search" />
  </div>

  <ul class="list uk-list uk-list-striped">
  {% for follower in followers %}
    <li>
      <table class="table uk-table">
          <tr>
            <td>
              <div class="image">
                {% if follower.profile_img_url %}
                  <img src="{{ follower.profile_img_url }}" style="height:90px;">
                {% else %}
                  <img src="{{ follower.avatar(90) }}">
                {% endif %}
              </div>
            </td>
            <td style="padding-left:10px">
              <p class="name">
                <a href="{{ url_for('users.profile', username=follower.username)
                  }}">{{ follower.username }}</a>
              </p>
              <p class="followers">
                {{ '%d followers' % follower.follower_count }}, {{ '%d
                following' % follower.followed_count }}
              </p>
            </td>
            <td style="padding-left:10px">
              {% if current_user.is_following(user) %}
                <a href="{{ url_for('api.follow', username=user.username) }}"
                  class="uk-button uk-button-primary js-toggle-follow" type="button"
                  data-username={{ user.username }}>Following</a>
              {% else %}
                <a href="{{ url_for('api.unfollow', username=user.username) }}"
                  class="uk-button uk-button-default js-toggle-follow" type="button" 
                  data-username={{ user.username }}>Follow</a>
              {% endif %}
            </td>
          </tr>
      </table>
    </li>
  {% endfor %}

  </ul>
  <ul class="pagination uk-pagination uk-flex-center"></ul>
</div>

src/app/templates/user/_followings.html
<div id="followings">
  <div class="uk-search uk-search-default">
    <span uk-search-icon></span>
    <input class="search uk-search-input" placeholder="Search" />
  </div>

  <ul class="list uk-list uk-list-striped">
  {% for followee in following %}
    <li>
      <table class="table uk-table">
          <tr>
            <td>
              <div class="image">
                {% if followee.profile_img_url %}
                  <img src="{{ followee.profile_img_url }}" style="height:90px;">
                {% else %}
                  <img src="{{ followee.avatar(90) }}">
                {% endif %}
              </div>
            </td>
            <td style="padding-left:10px">
              <p class="name">
                <a href="{{ url_for('users.profile', username=followee.username)
                  }}">{{ followee.username }}</a>
              </p>
              <p class="following">
                {{ '%d followings' % followee.followed.count() }}, {{ '%d
                following' % followee.followed.count() }}
              </p>
            </td>
            <td style="padding-left:10px">
              {% if current_user.is_following(user) %}
                <a href="{{ url_for('api.follow', username=user.username) }}"
                  class="uk-button uk-button-primary js-toggle-follow" type="button"
                  data-username={{ user.username }}>Following</a>
              {% else %}
                <a href="{{ url_for('api.unfollow', username=user.username) }}"
                  class="uk-button uk-button-default js-toggle-follow" type="button" 
                  data-username={{ user.username }}>Follow</a>
              {% endif %}
            </td>
          </tr>
      </table>
    </li>
  {% endfor %}
  </ul>
  <ul class="pagination uk-pagination uk-flex-center"></ul>
</div>

src/app/templates/user/discover.html
{% extends "base.html" %}

{% block app_content %}

<main class="uk-container">
  <h1 class="uk-heading-line"><span>Discover Users</span></h1>
  <div id="users">
    <div class="uk-search uk-search-default">
      <span uk-search-icon></span>
      <input class="search uk-search-input" placeholder="Search" />
    </div>
    <ul class="list uk-list uk-list-striped">

    {% for user in users %}
      <li>
        <table class="table uk-table">
          <tr>
            <td>
              <div class="image">
                {% if user.profile_img_url %}
                  <img src="{{ user.profile_img_url }}" style="height:90px;">
                {% else %}
                  <img src="{{ user.avatar(90) }}">
                {% endif %}
              </div>
            </td>
            <td style="padding-left:10px">
              <p class="name">
                <a href="{{ url_for('users.profile', username=user.username) }}">{{ user.username }}</a>
              </p>
              <p class="followers">
                {% if user.followers == true and user.followed == true %}
                {{ '%d followers' % user.followers.count() }}, {{ '%d following' % user.followed.count() }}
                {% endif %}
              </p>
            </td>
            <td style="padding-left:10px">
              {% if current_user.is_following(user) %}
                <a href="{{ url_for('api.follow', username=user.username) }}"
                  class="uk-button uk-button-primary js-toggle-follow" type="button"
                  data-username={{ user.username }}>Following</a>
              {% else %}
                {% if user == current_user %}
                  <button href="{{ url_for('api.unfollow', username=user.username) }}"
                    class="uk-button uk-button-disabled" type="button" 
                    data-username={{ user.username }} disabled>Follow</button>
                {% else %}
                  <a href="{{ url_for('api.unfollow', username=user.username) }}"
                    class="uk-button uk-button-default js-toggle-follow" type="button" 
                    data-username={{ user.username }}>Follow</a>
                {% endif %}
              {% endif %}
            </td>
          </tr>
        </table>
      </li>
    {% endfor %}

    </ul>
    <ul class="pagination uk-pagination uk-flex-center"></ul>
  </div>
</main>
{% endblock %}

src/app/templates/user/edit_profile.html
{% extends "base.html" %}

{% block app_content %}
<main class="uk-container">
  <div class = "profile">
    <h1 class = "uk-heading-line"><span>Edit Profile</span></h1>
    <form action="{{ url_for('users.edit_profile') }}" method="POST" enctype="multipart/form-data">
      <fieldset class="uk-fieldset">
        {{ form.hidden_tag() }}

        <div class = "uk-flex uk-flex-center uk-padding">
          <img id="target" src="{{ current_user.profile_img_url or
          current_user.avatar(256) }}" style="height:256px;" alt="your image" />
        </div>

        <div class="uk-margin">
            <div uk-form-custom>
          {{ form.profile_img(class_="imgInp uk-input") }}
          <button class="uk-button" type="button" tabindex="-1">Upload Photo</button>
        </div>
        </div>
        <div class="uk-margin">
          {{ form.username.label }}<br>
          {{ form.username(class_="uk-input") }}<br>
          {% for error in form.username.errors %}
            <span class="uk-text-danger">
          {% endfor %}
        </div>
        <div class="uk-margin">
          {{ form.bio.label }}<br>
          {{ form.bio(class_="uk-textarea", placeholder="Caption") }}
          {% for error in form.bio.errors %}
            <span class="uk-text-danger">
          {% endfor %}
        </div>
        {{ form.submit(class_="uk-button uk-button-default") }}
      </fieldset>
    </form>
  </div>
</main>
{% endblock %}

src/app/templates/user/profile.html
{% extends "base.html" %}

{% block app_content %}
<main class="uk-container">
  <div class = "profile">
    <h1 class = "uk-heading-line"><span>Profile</span></h1>

    <div class = "image">
      <div class = "uk-flex uk-flex-center uk-padding">
        {% if user.profile_img_url %}
          <img src="{{ user.profile_img_url }}" style="height:256px;">
        {% else %}
          <img src="{{ user.avatar(256) }}">
        {% endif %}
      </div>
    </div>

    <div class = "description uk-text-center">
      {% if user.bio %}
        <p>{{ user.bio }}</p>
      {% endif %}
    </div>

    <div class = "action">
      <div class="uk-flex uk-flex-center">
        {% if user == current_user %}
          <a href="{{ url_for('users.edit_profile') }}" class="uk-button
            uk-button-default">Edit Profile</a> 
        {% endif %}
        {% if not user == current_user %}
          {% if current_user.is_following(user) %}
            <a href="{{ url_for('api.follow', username=user.username) }}"
              class="uk-button uk-button-primary js-toggle-follow" type="button"
              data-username={{ user.username }}>Following</a>
          {% else %}
            <a href="{{ url_for('api.unfollow', username=user.username) }}"
              class="uk-button uk-button-default js-toggle-follow" type="button" 
              data-username={{ user.username }}>Follow</a>
          {% endif %}
        {% endif %}

      </div>
    </div>

    <h3 class = "uk-heading-line uk-text-right"><span>{{ user.username}}</span></h3>
  </div>

  <div class = "content">
    <ul class="uk-subnav uk-subnav-pill uk-flex-center" uk-switcher>
      {% if user.posts %}
        <li><a href="#">Posts</a></li>
      {% endif %}
        <li><a href="#">{{ user.follower_count }} Followers</a></li>
        <li><a href="#">{{ user.followed_count }} Followings</a></li>
    </ul>
    <ul class="uk-switcher uk-margin">
      <li>
        <div>
          {% include 'posts/_posts.html' %}
          {% if next_url %}
            <a class="npage" hidden href={{ next_url or "#" }}>next_url</a>
          {% endif %}
        </div>
      </li>
      <li>{% include 'user/_followers.html' %}</li>
      <li>{% include 'user/_followings.html' %}</li>
    </ul>
  </div>

</main>
{% endblock %}